### PR TITLE
customization of colors and systray icon

### LINKED ISSUE #13: Customization, fonts and systray
It would be nice to be able to customize:
- background color `--bgcolor #0F0F0F`
- font color `--fontcolor #FFFFFF`
- do not show system tray icon `--no-systray`

### PR DESCRIPTION
**Pull request by 4e6**
added flags:
- --bgcolor #0F0F0F, background color
- --fontcolor #FFFFFF, font color
- --no-systray, do not show system tray icon

fixes #13

### CODE REVIEW

**Comment by wavexx** [comment]
I would remove the debug log "Systray not loaded", since you're explicitly requesting for it. Apart from that, everything else is good.

**Comment by 4e6** [comment]
Done!

**Comment by wavexx** [comment]
I also added these to the settings dialogs now. And opacity, why not...

**Comment by 4e6** [comment]
Oh, very nice, thank you. My bad, I completely forgot about settings dialog.

**Pull request merged**
