### PR TITLE
set font size with respect to dpi

### LINKED ISSUE #9: HiDPI display support
With DPI higher than 96, default value, screenkey fails with `'BadAlloc (insufficient resources for operation)'` 

```
The program 'screenkey' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadAlloc (insufficient resources for operation)'.
  (Details: serial 518 error_code 11 request_code 53 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

This happens because function [`override_font_attributes`](https://github.com/wavexx/screenkey/blob/c54bd0c8936d0fd22f315d45abef5f56c080fc29/Screenkey/screenkey.py#L192) calculates `AttrSize` font value larger than current window height can handle. That leads to recursive resizing of window (each window resize event results in call to `override_font_attributes`).

### PR DESCRIPTION
**Pull request by 4e6**
Calculate font size considering DPI of the current display. Function `get_screen_dpi` returns DPI based on `gtk-xft-dpi` [Screen setting](http://www.pygtk.org/pygtk2reference/class-gtksettings.html) with fallback to default value (original logic).

fixes #9

### CODE REVIEW

**Comment by wavexx** [comment]
Good catch, but I suspect it might be not enough?. DPI can be set per-output using XRandR (yes, I'm actually changing DPI to 150+ but didn't notice this problem so far?), so at minimum we need to get the DPI of `self.monitor`. Depends on where pango gets his DPI value.

Strictly speaking, the output window is auto-sized, so it would be nice to set the font size by pixel-size directly. It looks like this is not supported by pango?...

**Comment by wavexx** [comment]
Of course there's also an absolute size attribute (AttrSizeAbsolute), which avoids the DPI scaling. I briefly tested it here by manipulating the `Xft.dpi` resource and seems to work as intended. Could you give it a shot?

**Comment by 4e6** [comment]
My `Xft.dpi` set to 210

```
> grep dpi ~/.Xresources
Xft.dpi:                  210
> xdpyinfo | grep -B2 resolution
screen #0:
  dimensions:    2560x1440 pixels (311x176 millimeters)
  resolution:    209x208 dots per inch
```

Nice detail, didn't know about absolute version of `AttrSize` function. I can confirm that 5fdc19feb5c1d30a09f16e1ca9c329320e7fe706 fixes the issue.

**Comment by wavexx** [comment]
On 06/09/15 11:59, Dmitry Bushev wrote:

> My |Xft.dpi| set to 210

I re-discovered I had set manually Xft.dpi to 96 due to the external
monitor usually being lower-res :/. It was causing me headaches when
moving windows from-to the external monitor.

It looks like almost nobody actually does per-output scaling correctly,
and those who do use the XRandR value instead of the X resource.

> https://github.com/wavexx/screenkey/commit/5fdc19feb5c1d30a09f16e1ca9c329320e7fe706
> fixes the issue.

Did you notice any other issue?
If not, I think this deserves a quick release.

**Comment by 4e6** [comment]
Tried different sizes, positions and custom geometry. Looks good to me.

**Comment by 4e6** [comment]
Although, I've managed to find another small one #11

**Comment by wavexx** [comment]
Oh well, I also fixed another issue involving the stored geometry (couldn't reset after an interactive resize).

**Pull request closed without merging**
