### PR TITLE
Abbreviations for lvl5 and layout switch.

### PR DESCRIPTION
**Pull request by seletskiy**
I'm using `ISO_Level5_Shift` as additional modifier and it takes a lot of space in the screenkey panel.

### CODE REVIEW

**Comment by wavexx** [comment]
On 23/10/15 12:01, Stanislav Seletskiy wrote:

> I'm using `ISO_Level5_Shift` as additional modifier and it takes a
> lot of space in the screenkey panel.

Do you have a picture of the actual keyboard?
I'm curious on what Lvl5 and Mode_Switch actually look like.

I had some old Sun keyboards with a slew of extra remappable keys, but I
guess this is not the case.

**Comment by seletskiy** [comment]
It's just an ordinary mechanical keyboard, I use RAlt as ISO_Level5_Shift
to remap various keys for more productive work, like RAlt+w is "6".
However, Mode_Switch is controlled via foot-pedal under my table :)

**Comment by wavexx** [comment]
So both keys are simply modifiers?

Could you share your Mode_Switch customization? I also have a kinesis with 3 foot switches, and I'd like to try how it works (I normally use them as shift+ctrl+enter).

I internally translate Mode_switch as AltrGr in the MODS_MAP, which I guess the actual translation should take place is both are just modifiers and not actual (direct) keys.

**Comment by seletskiy** [comment]
@wavexx: I'm configuring my binding using raw XKB configs, because it's most flexible (and most ugly!) way to do it.

I'm [using little tool called `footswitch`](https://github.com/seletskiy/dotfiles/blob/master/bin/reconfig-kbd#L21) to map pedals to other keys. I've chosen easiest way and have mapped pedals to <kbd>F6</kbd>, <kbd>F7</kbd>, <kbd>F8</kbd>. Then, I've [remapped](https://github.com/reconquest/rex/blob/563b9233f9c8b586bb7be8d3140a93bf7783ae0f/symbols/footswitch) F7 to <kbd>Multi Key</kbd> (compose) and F8 to secondary layout (Russian, while pedal is pressed).

So, yep, keys are just modifiers.

But speaking about <kbd>ISO_Level5_Shift</kbd> it's not just modifier (in terms of XKB), it's more like separate layer of keys, so when I press <kbd>RAlt</kbd>+<kbd>w</kbd> it's actually seen by X11 as plain <kbd>6</kbd> key press without any modifier, so I can type <kbd>RAlt</kbd>+<kbd>Shift</kbd>+<kbd>w</kbd> to type <kbd>^</kbd>.

So, screenkey by itself sees <kbd>RAlt</kbd>+<kbd>w</kbd> as two different key presses: <kbd>Lvl5</kbd> and <kbd>6</kbd>. It's somewhat confusing, maybe we need to add `--ignore` flag to completely ignore `Lvl5`? What do you think?

BTW, I use same mechanism to remap arrow keys on <kbd>LAlt</kbd>+<kbd>h</kbd>, <kbd>j</kbd>, <kbd>k</kbd>, <kbd>l</kbd> **system-wide** in that way, so it works in all applications including GUI like Chrome. I found it immensely useful and highly recommend to do the same.

**Comment by wavexx** [comment]
On 26/10/15 11:29, Stanislav Seletskiy wrote:

> BTW, I use same mechanism to remap arrow keys on
> <kbd>LAlt</kbd>+<kbd>h</kbd>, <kbd>j</kbd>, <kbd>k</kbd>,
> <kbd>l</kbd> **system-wide** in that way, so it works in all
> applications including GUI like Chrome. I found it immensely useful
> and highly recommend to do the same.

I'm thinking of some way that could be more "elegant" than a simple
ignore list, but well...

The only thing is having some decent way to add/remove them in the
settings pane as well.

This could come in handy if you want to hide, for example, cursor keys
from the output (which is something that I wanted to do sometimes while
teaching). Just add them to the ignore list.

**Comment by seletskiy** [comment]
@wavexx: That's why I don't like GUI. In CLI it's just adding `--ignore`.

**Comment by wavexx** [comment]
It wouldn't be too much of a problem normally, but the settings dialog is still containing a _lot_ of crufty code which will need to get killed at some point. None of that works with Gtk3 anymore. One of the few parts I was too lazy to rewrite...

I think I'll just slip in the flag for now. I think the best approach would simply be:

```
--ignore [KeySym]
```

and repeat the flag if you need to ignore more keys.

**Comment by wavexx** [comment]
I added the --ignore flag. Just repeat the flag to ignore more than one KeySym. It's also loaded from the 'ignore' array from the json config. There's no GUI for that yet.

**Comment by wavexx** [comment]
Hopefully fixed in 0.8. Let me know if you have a better idea on how to handle it.

**Comment by seletskiy** [comment]
@wavexx: Thanks! It's awesome!

On Wed, Nov 4, 2015 at 5:06 PM, wavexx notifications@github.com wrote:

> Closed #15 https://github.com/wavexx/screenkey/pull/15.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/wavexx/screenkey/pull/15#event-454329665.

## 

Stanislav Seletskiy

**Pull request closed without merging**
