### PR TITLE
partially fixing issue #43

### PR DESCRIPTION
**Pull request by khalilfazal**
What works:

- [x] images for mouse buttons shows up properly: smooth transition between key presses (`gtk.Label`) and mouse clicks (`gtk.Image`)
- [x] images for mouse buttons:
    - [x] left, middle, and right mouse buttons
    - [x] scroll up/down
    - [x] scroll left/right

TODO:
- [ ] Change the mouse image's aspect (size, color, opacity) with respect to options
- [ ] add option to show the buttons on top of the cursor (requested by @ChameleonScales) instead of where keys normally appear on the bottom
- [ ] add a mouse circling feature better than keymon's

### CODE REVIEW

**Comment by ChameleonScales** [comment]
Thank you very much for tackling this.
I dowloaded the fork and ran screenkey but I don't see any mouse icon though.

**Comment by khalilfazal** [comment]
What's the output of running it in debug mode and mashing your mouse buttons?
Mouse icon appears on mouse clicks.

`screenkey -d`

**Comment by ChameleonScales** [comment]
Nothing appears. Only when I press keys.
I downloaded the fork [here](https://github.com/khalilfazal/screenkey).

**Comment by khalilfazal** [comment]
Ah, that's the wrong link.  
The link you just gave is a link to the master branch.
This is the right link: https://github.com/khalilfazal/screenkey/tree/fork
Sorry, I did it awkwardly.

You can tell by whether my commits are included or not.

**Comment by ChameleonScales** [comment]
Oh yes it works great now !

**Comment by ChameleonScales** [comment]
and you did the scroll wheel today

**Comment by ChameleonScales** [comment]
One issue though is that it disappears as soon as you hit a key and vice versa
it would be great if both could be displayed together.
So the icon would have to be on the left or right side to make room for the letters.

**Comment by ChameleonScales** [comment]
Also it has trouble changing the size :
If you go bigger it changes the size as soon as you hit a key or mouse button but if you go smaller (large to medium or medium to small) it only works when you wait until the bar disappears and hit a key (not a mouse button).

**Comment by ChameleonScales** [comment]
2 other things :
- The hatching filling of the buttons looks nice but I'd prefer them to be filled entirely to be more visible, especially when using the small display size. Having the choice between the 2 in the preferences would be the best.
- (less important for me right now) the "Font color" property only applies to text, not the mouse icon. It would be great to have it work on both, although I know it's more complicated to implement.

**Comment by wavexx** [comment]
Should we close this in favor of #65, or there is something extra?

**Comment by ChameleonScales** [comment]
for what concerns me, we can close it, there's no additional functionality to it.

**Comment by wavexx** [comment]
Ok, closing then to reduce the list of duplicate PRs

**Pull request closed without merging**
