### PR TITLE
Option to always show the text

### PR DESCRIPTION
**Pull request by Invertisment**

### CODE REVIEW

**Comment by wavexx** [comment]
If this is to show the window, then `--persist` is there already.

**Comment by Invertisment** [comment]
Nope. This is for the text itself. It hides inside of the window

**Comment by wavexx** [comment]
On Fri, Nov 18 2016, Martin wrote:

> Nope. This is for the text itself. It hides inside of the window

This will incur in bad performance in a few minutes of usage though, and
the rendering of the gtk label is by far not fast.

If the width is larger than displayed, we should truncate the internal
buffer appropriately.

**Comment by Invertisment** [comment]
Have you tried it? Does it cause flickering?

**Comment by Invertisment** [comment]
It looks like the string is trimmed somewhere inside gtk component.

screenshot-13

**Comment by Invertisment** [comment]
Hmm.
I googled a bit and found these two functions:

```
pango_glyph_string_extents
pango_glyph_string_get_width
```

https://sourcecodebrowser.com/pango1.0/1.14.8/glyphstring_8c.html#a0ea1dc42170be3e867affba7bd869faf

Can we use them to determine the length of the visible string and then manually trim it away?
I don't know how to get `PangoGlyphString` from `label`

**Comment by wavexx** [comment]
On Fri, Nov 18 2016, Martin wrote:

> Have you tried it? Does it cause flickering?

I'm a bit busy this weekend, I hope to try in the following days.

**Comment by Invertisment** [comment]
Alright. I made a change to limit the buffer size if there is no timeout specified.
Actually I decided to make a separate buffer with key press counts. It looked broken if user inputs same key many times and with new keys the count decreases.

For now user may decide what buffer size is sufficient. Later it may be possible to determine it automatically (if we bump the GTK version for those functions that I mentioned earlier).

What I may have broken is the code that is commented out. If you could verify that everything works, I will be able to remove it. It is in the file `Screenkey/labelmanager.py`, lines 293 and 299.
I would appreciate if you could verify if all features still work and the code that was removed was replaced properly.

**Comment by wavexx** [comment]
What if we handle a timeout of "0" as "no timeout"? I'd like to avoid an extra option.

**Comment by Invertisment** [comment]
"0" as no timeout is fine.

**Pull request closed without merging**
